### ISSUE TITLE
Geolocalization button needs icon

### ISSUE THREAD

**Issue by javierlopezdeancos** [gdgtoledo/katangapp-android#23]
Geolocalization button needs an icon, this icon is in mockups defined

**Comment by mdelapenya** [comment]
@javierlopezdeancos which repo are the mockups in?

**Comment by javierlopezdeancos** [comment]
jajaja we have katangapp-ux in github? I can put there all the scketch files or svg

**Comment by mdelapenya** [comment]
merged, thanks!
