### ISSUE TITLE
Remove image on main activity background

### ISSUE THREAD

**Issue by mdelapenya** [gdgtoledo/katangapp-android#42]
Otherwise, it cannot not fit to all devices' screens

**Comment by javierlopezdeancos** [comment]
In my UX opinion, In the desktop aproach I try to do the same, the screens flow should be
- screen yellow with katanga logo ( icon and text in the midlle of screen )
- before 1,5/2 seconds , black screen with slider and geo button :)

more easy more clean and more useful

**Comment by javierlopezdeancos** [comment]
maybe the first screen can be white background and logo with circle yellow in the middle

**Comment by mdelapenya** [comment]
👍

**Comment by mdelapenya** [comment]
Merged, thanks!

![image](https://media.giphy.com/media/4Z3DdOZRTcXPa/giphy.gif)

**Comment by mdelapenya** [comment]
Hey @javierlopezdeancos we added your input and it looks really really good 😃
